### PR TITLE
files required to fill the db in neurovault

### PR DESCRIPTION
**Pull request by erramuzpe**

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Could you:
1. Remove the .npy files from the data dump (they should be generated upon loading of the fixture)
2. Squash everything into one commit and force push. Git is pretty bad at dealing with differences between binary files. Updating one zip file in multiple commits will blow up the repo size.

**Comment by erramuzpe** [comment]
1.- OK!
2.- OK!

nice :)

**Comment by chrisgorgo** [comment]
Almost there!

There is one remaining problem that bothers me: you reuse the same file multiple times in one collection (4). This can be perceived an artefact of a bug when people develop using these fixture. It would be better to keep the fixture data real and not duplicate images.

**Comment by erramuzpe** [comment]
I was not aware of this, all the files where downloaded from a random collection. I will change the dulpicates right away

**Comment by erramuzpe** [comment]
wait, I have to change this: "NIDMResults has no field named 'provn_file'

**Comment by cmaumet** [comment]
I don't know if this helps but provn serialisation is no longer provided in a NIDM-Results pack (only the turtle serialisation is). Are you using the provn serialisation on NeuroVault?

**Comment by erramuzpe** [comment]
I think we were using it, but not anymore, so I removed it from the fixture. It works now, but I still see the repeated statmaps, so I will change them again (probably I changed them wrongly).

**Comment by chrisgorgo** [comment]
Yes - I just removed it.

**Comment by erramuzpe** [comment]
is it ok now? 

leaving, have a good weekend! :dancer:

**Pull request merged**
